# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9ae812234a7ca5929614cdd3881dddc390045ebca9db1d9751364e579b61d2b8b8697dfdbb36c5807b44397584d8f05dc21f33b79572295a13402abff01086a

test:
  secret_key_base: 2e4bb847ede9c5686665a0e5745fe6920c07a9a8feadcfa1d353e557fd59fc0a69f5de2b4b0ba7d8cf2dd8a68302167fcdc250897026b57c02aa7f2ca64c4cf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
